export const UIText = {
    title: "Address Book Menu",
    linkList: "Contacts List",
    linkAdd: "Contact Add New",
    contactAddTitle: "Create Contact",
    contactFirst: "First Name",
    contactLast: "Last Name",
    contactStreet: "Street",
    contactCity: "City",
    contactAddButton: "Create",
    contactDeleteTitle: "Delete Contact",
    contactDeleteConfirm: "Are you sure you want to delete this contact?",
    contactEditTitle: "Edit Contact",
    contactEditButton: "Edit",
    contactListTitle: "Contacts",
    contactListView: "View",
    contactListEdit: "Edit",
    contactListDelete: "Delete",
    contactViewTitle: "Contact Info",
    contactViewNone: "No Such Contact..."
}